const menu = [
  {id:'og',name:'OG Matcha Taho',category:'Classics',price:7.50,desc:'Ceremonial matcha, silken taho, sago & house arnibal.',flavour:'#82a54f',bg:'#e4e8cb',glow:'#c8d88d',badge:'MATSYA CLASSIC',plant:true,emoji:'🍵'},
  {id:'strawberry',name:'Strawberry Matcha',category:'Fruity',price:8.25,desc:'Real strawberry compote, matcha, taho & chewy sago.',flavour:'#db8c87',bg:'#f1ded5',glow:'#e8b6af',badge:'BESTSELLER',plant:true,emoji:'🍓'},
  {id:'ube',name:'Ube Matcha Taho',category:'Filipino Faves',price:8.50,desc:'Creamy ube halaya, matcha, taho & toasted coconut.',flavour:'#95789a',bg:'#e6dce6',glow:'#c8afcd',badge:'FILIPINO FAVE',plant:true,emoji:'🍠'},
  {id:'mango',name:'Mango Matcha',category:'Fruity',price:8.25,desc:'Philippine mango purée, matcha, taho & sago.',flavour:'#e2ac49',bg:'#f2e6c7',glow:'#efcd7a',badge:'SEASONAL',plant:true,emoji:'🥭'},
  {id:'calamansi',name:'Calamansi Cloud',category:'Fruity',price:8.00,desc:'Bright calamansi curd, coconut cloud and matcha taho.',flavour:'#bac454',bg:'#e8ebc7',glow:'#d8df79',plant:true,emoji:'🍋'},
  {id:'brown-sugar',name:'Brown Sugar Kinako',category:'Classics',price:8.00,desc:'Roasted soybean, dark arnibal, matcha & extra sago.',flavour:'#948053',bg:'#e8dfcb',glow:'#cdbb92',plant:true,emoji:'🫘'},
  {id:'buko',name:'Buko Pandan Matcha',category:'Filipino Faves',price:8.50,desc:'Young coconut, pandan jelly, matcha and silken taho.',flavour:'#6f9f72',bg:'#dbe7d4',glow:'#aacfaa',badge:'NEW',plant:true,emoji:'🥥'},
  {id:'cookie',name:'Tsokolate Cookie',category:'Indulgent',price:8.75,desc:'Tablea chocolate, matcha, cookie crumble and taho.',flavour:'#7a523d',bg:'#e8d9ce',glow:'#c79d84',plant:false,emoji:'🍫'},
  {id:'black-sesame',name:'Black Sesame Matcha',category:'Indulgent',price:8.50,desc:'Nutty black sesame cream, matcha, tofu and arnibal.',flavour:'#5c605b',bg:'#dde0da',glow:'#afb7ad',plant:true,emoji:'🖤'}
];
const statuses=['New','Confirmed','Preparing','Ready','Out for delivery','Delivered'];
const state={cart:JSON.parse(localStorage.getItem('matsya-cart')||'[]'),orders:JSON.parse(localStorage.getItem('matsya-orders')||'null')||seedOrders(),category:'All',plantOnly:false,selected:null,options:{},qty:1,payment:'Card',adminTab:'dashboard',orderFilter:'All'};
function seedOrders(){return[
  {id:'MT-1083',name:'Alex Rivera',phone:'416-555-0142',address:'18 Tecumseth St, Toronto',items:[{id:'ube',name:'Ube Matcha Taho',qty:2,price:8.5,size:'Regular',sweetness:'Regular'}],total:21.81,status:'Preparing',eta:24,time:'10:42 AM',payment:'Paid · Card'},
  {id:'MT-1082',name:'Sofia Santos',phone:'647-555-0198',address:'55 East Liberty St, Toronto',items:[{id:'strawberry',name:'Strawberry Matcha',qty:1,price:8.25,size:'Large',sweetness:'Less'}],total:13.28,status:'Ready',eta:16,time:'10:35 AM',payment:'Paid · Apple Pay'},
  {id:'MT-1081',name:'Noah Kim',phone:'416-555-0181',address:'20 Minowan Miikan Ln, Toronto',items:[{id:'og',name:'OG Matcha Taho',qty:2,price:7.5,size:'Regular',sweetness:'Regular'},{id:'mango',name:'Mango Matcha',qty:1,price:8.25,size:'Regular',sweetness:'Less'}],total:28.85,status:'Out for delivery',eta:8,time:'10:21 AM',payment:'Paid · Card'}
]}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n);
function save(){localStorage.setItem('matsya-cart',JSON.stringify(state.cart));localStorage.setItem('matsya-orders',JSON.stringify(state.orders))}
function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toastStack').append(el);setTimeout(()=>el.remove(),3000)}
function productCard(p){return `<article class="product-card" data-product="${p.id}"><div class="product-art" style="--art-bg:${p.bg};--art-glow:${p.glow};--flavour:${p.flavour}">${p.badge?`<span class="product-badge">${p.badge}</span>`:''}<button class="heart" aria-label="Save ${p.name}">♡</button><span class="cup"></span></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><strong>from ${money(p.price)}</strong><button class="add-button" data-add="${p.id}" aria-label="Add ${p.name}">+</button></div></div></article>`}
function renderProducts(){
  $('#featuredGrid').innerHTML=menu.slice(0,3).map(productCard).join('');
  const categories=['All',...new Set(menu.map(x=>x.category))];
  $('#categoryTabs').innerHTML=categories.map(c=>`<button class="${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('');
  const filtered=menu.filter(p=>(state.category==='All'||p.category===state.category)&&(!state.plantOnly||p.plant));
  $('#menuGrid').innerHTML=filtered.map(productCard).join('')||'<div class="empty-state"><h3>No cups found</h3><p>Try another filter.</p></div>';
}
function go(page){
  $$('.page').forEach(p=>p.classList.remove('active')); const target=$(`#${page}Page`)||$('#homePage'); target.classList.add('active');
  $$('.nav-link,.mobile-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===page));
  if(page==='admin')renderAdmin(); window.scrollTo({top:0,behavior:'smooth'});
}
function openProduct(id){
  const p=menu.find(x=>x.id===id); if(!p)return; state.selected=p;state.qty=1;state.options={size:'Regular',sweetness:'Regular',milk:'Oat',topping:'None'};
  $('#productModalContent').innerHTML=`<div class="product-modal-content"><div class="modal-art" style="--art-bg:${p.bg};--flavour:${p.flavour}"><span class="cup"></span></div><div class="modal-options"><span class="kicker">${p.category}</span><h2>${p.name}</h2><p>${p.desc}</p>${optionGroup('size','Choose a size',['Regular','Large +$1.25'])}${optionGroup('sweetness','Sweetness',['Light','Regular','Extra'])}${optionGroup('milk','Matcha milk',['Oat','Coconut','Whole'])}${optionGroup('topping','Add a topping',['None','Extra sago +$0.75','Coconut cloud +$1'])}<div class="add-modal-row"><div class="large-qty"><button data-modal-qty="-1">−</button><b id="modalQty">1</b><button data-modal-qty="1">+</button></div><button class="primary-button" id="confirmAdd">Add to basket · <span id="modalPrice">${money(p.price)}</span></button></div></div></div>`;
  openLayer($('#productModal'));
}
function optionGroup(key,label,values){return `<div class="option-group"><div class="option-head"><b>${label}</b><small>${key==='size'?'Required':'Choose one'}</small></div><div class="option-pills">${values.map((v,i)=>`<button data-option="${key}" data-value="${v}" class="${i===0&&key!=='sweetness'?'active':(v==='Regular'?'active':'')}">${v}</button>`).join('')}</div></div>`}
function optionExtra(){let x=0;if(state.options.size?.startsWith('Large'))x+=1.25;if(state.options.topping?.includes('$0.75'))x+=.75;if(state.options.topping?.includes('$1'))x+=1;return x}
function updateModalPrice(){if(!state.selected)return;$('#modalQty').textContent=state.qty;$('#modalPrice').textContent=money((state.selected.price+optionExtra())*state.qty)}
function addSelected(){const p=state.selected;const price=p.price+optionExtra();state.cart.push({key:Date.now(),id:p.id,name:p.name,qty:state.qty,price,size:state.options.size.replace(' +$1.25',''),sweetness:state.options.sweetness,milk:state.options.milk,topping:state.options.topping,colour:p.bg});save();renderCart();closeLayers();toast(`${p.name} added to your basket`)}
function renderCart(){
  const count=state.cart.reduce((a,x)=>a+x.qty,0);['#cartCount','#mobileCartCount'].forEach(s=>$(s).textContent=count);$('#drawerCount').textContent=`${count} item${count===1?'':'s'}`;
  if(!state.cart.length){$('#cartItems').innerHTML='<div class="cart-empty"><span style="font-size:38px">🍵</span><b>Your basket is empty</b><p>A fresh cup of joy is waiting.</p><button class="primary-button" data-go="menu" data-close>Browse the menu →</button></div>';$('#cartSummary').innerHTML='';return}
  $('#cartItems').innerHTML=state.cart.map((x,i)=>`<div class="cart-row"><div class="mini-cup" style="--mini:${x.colour}">${menu.find(p=>p.id===x.id)?.emoji||'🍵'}</div><div><h4>${x.name}</h4><p>${x.size} · ${x.sweetness} sweet · ${x.milk}</p>${x.topping!=='None'?`<p>+ ${x.topping}</p>`:''}<div class="qty"><button data-cart-qty="${i}" data-delta="-1">−</button><span>${x.qty}</span><button data-cart-qty="${i}" data-delta="1">+</button></div></div><div><strong>${money(x.price*x.qty)}</strong><button class="remove" data-remove="${i}">Remove</button></div></div>`).join('');
  const sub=state.cart.reduce((a,x)=>a+x.price*x.qty,0),delivery=4.49,tax=sub*.13,total=sub+delivery+tax;
  $('#cartSummary').innerHTML=`<div class="summary-line"><span>Subtotal</span><b>${money(sub)}</b></div><div class="summary-line"><span>Delivery</span><b>${money(delivery)}</b></div><div class="summary-line"><span>HST</span><b>${money(tax)}</b></div><div class="summary-line total"><span>Total</span><b>${money(total)}</b></div><button class="primary-button checkout-button" id="checkoutButton">Checkout · ${money(total)} <span>→</span></button>`;
}
function openLayer(el){$('#overlay').classList.add('active');el.classList.add('active');document.body.style.overflow='hidden'}
function closeLayers(){$('#overlay').classList.remove('active');$$('.drawer,.modal').forEach(x=>x.classList.remove('active'));document.body.style.overflow=''}
function openCheckout(){
  if(!state.cart.length)return;const sub=state.cart.reduce((a,x)=>a+x.price*x.qty,0),total=sub+4.49+sub*.13;
  $('#checkoutContent').innerHTML=`<div class="checkout-wrap"><span class="kicker">Secure checkout</span><h2>Almost time for merienda.</h2><div class="checkout-layout"><form id="checkoutForm"><div class="checkout-section"><h3>Delivery details</h3><div class="form-grid"><div class="field"><label>Full name</label><input name="name" required placeholder="Juan dela Cruz"></div><div class="field"><label>Phone</label><input name="phone" required placeholder="(416) 555-0123"></div><div class="field full"><label>Delivery address</label><input name="address" required placeholder="123 Queen St W, Toronto"></div><div class="field full"><label>Unit / delivery notes</label><textarea name="notes" rows="2" placeholder="Buzz code, allergies, or rider instructions"></textarea></div></div></div><div class="checkout-section"><h3>When?</h3><div class="option-pills"><button type="button" class="active">As soon as possible · 25–35 min</button><button type="button">Schedule</button></div></div><div class="checkout-section"><h3>Payment</h3><div class="payment-options"><button type="button" class="active" data-payment="Card">💳 Card</button><button type="button" data-payment="Apple Pay"> Pay</button><button type="button" data-payment="Cash">Cash</button></div><div class="form-grid" id="cardFields" style="margin-top:10px"><div class="field full"><label>Card number</label><input inputmode="numeric" placeholder="4242 4242 4242 4242" value="4242 4242 4242 4242"></div><div class="field"><label>Expiry</label><input placeholder="MM / YY" value="12 / 28"></div><div class="field"><label>CVC</label><input placeholder="123" value="123"></div></div></div><button class="primary-button checkout-button" type="submit">Place order · ${money(total)} <span>→</span></button><p style="font-size:8px;color:#8a918c;text-align:center">🔒 Demo checkout — no real payment is processed.</p></form><aside class="order-mini-summary"><h3>Your order</h3>${state.cart.map(x=>`<div class="checkout-item"><span>${x.qty}× ${x.name}</span><b>${money(x.qty*x.price)}</b></div>`).join('')}<div class="summary-line"><span>Delivery</span><b>${money(4.49)}</b></div><div class="summary-line"><span>HST</span><b>${money(sub*.13)}</b></div><div class="summary-line total"><span>Total</span><b>${money(total)}</b></div></aside></div></div>`;
  $('#cartDrawer').classList.remove('active');openLayer($('#checkoutModal'));
}
function placeOrder(form){
  const data=Object.fromEntries(new FormData(form)),sub=state.cart.reduce((a,x)=>a+x.price*x.qty,0);const id=`MT-${1084+state.orders.filter(o=>Number(o.id.slice(3))>=1084).length}`;
  const order={id,name:data.name,phone:data.phone,address:data.address,notes:data.notes,items:structuredClone(state.cart),total:sub+4.49+sub*.13,status:'New',eta:35,time:new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),payment:state.payment==='Cash'?'Cash on delivery':`Paid · ${state.payment}`};state.orders.unshift(order);state.cart=[];save();renderCart();closeLayers();$('#trackInput').value=id;renderTracking(order);go('track');toast(`Order ${id} confirmed!`);
}
function renderTracking(order){
  if(!order){$('#trackingResult').className='tracking-result empty-state';$('#trackingResult').innerHTML='<span>?</span><h3>Order not found</h3><p>Check your order number and try again.</p>';return}
  const stages=['Confirmed','Preparing','Out for delivery','Delivered']; let idx=order.status==='New'?0:Math.max(0,stages.indexOf(order.status));if(order.status==='Ready')idx=1;
  $('#trackingResult').className='tracking-result';$('#trackingResult').innerHTML=`<div class="track-top"><div><span class="kicker">Order ${order.id}</span><h2>Hi ${order.name.split(' ')[0]}, your cup is ${order.status==='Delivered'?'here!':'in good hands.'}</h2><small>${order.items.reduce((a,x)=>a+x.qty,0)} item(s) · ${money(order.total)}</small></div><span class="status-chip">${order.status}</span></div><div class="eta-box"><div><small>Estimated arrival</small><b>${order.status==='Delivered'?'Delivered':`${order.eta}–${order.eta+8} minutes`}</b></div><span style="font-size:35px">${order.status==='Out for delivery'?'🛵':'🍵'}</span></div><div class="progress-line">${stages.map((s,i)=>`<span class="progress-step ${i<=idx?'done':''}">${s}</span>`).join('')}</div><div class="track-details"><div><h4>Delivering to</h4><p>${order.address}<br>${order.notes||'No delivery notes'}</p></div><div><h4>Your order</h4><p>${order.items.map(x=>`${x.qty}× ${x.name} (${x.size})`).join('<br>')}<br><b>${order.payment}</b></p></div></div>`;
}
function adminStats(){const active=state.orders.filter(o=>o.status!=='Delivered'),revenue=state.orders.reduce((a,o)=>a+o.total,0),cups=state.orders.flatMap(o=>o.items).reduce((a,x)=>a+x.qty,0);return{active,revenue,cups}}
function statusOptions(order){return statuses.map(s=>`<option ${s===order.status?'selected':''}>${s}</option>`).join('')}
function ordersTable(orders){return `<table class="order-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>ETA</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${o.id}</b><small>${o.time}</small></td><td><b>${o.name}</b><small>${o.address.split(',')[0]}</small></td><td>${o.items.reduce((a,x)=>a+x.qty,0)} cup(s)</td><td><b>${money(o.total)}</b><small>${o.payment}</small></td><td><span class="status-dot"></span><select data-status-order="${o.id}">${statusOptions(o)}</select></td><td><select data-eta-order="${o.id}">${[8,12,16,20,25,30,35,45].map(n=>`<option ${n===o.eta?'selected':''} value="${n}">${n} min</option>`).join('')}</select></td></tr>`).join('')}</tbody></table>`}
function renderAdmin(){
  const {active,revenue,cups}=adminStats();$('#newOrderBadge').textContent=state.orders.filter(o=>o.status==='New').length;
  if(state.adminTab==='dashboard'){$('#adminContent').innerHTML=`<div class="stats-grid"><div class="stat-card"><span>ORDERS TODAY</span><strong>${state.orders.length}</strong><small>↑ Live customer orders</small></div><div class="stat-card"><span>NET SALES</span><strong>${money(revenue)}</strong><small>↑ 12.4% vs yesterday</small></div><div class="stat-card"><span>ACTIVE ORDERS</span><strong>${active.length}</strong><small>${state.orders.filter(o=>o.status==='New').length} waiting to confirm</small></div><div class="stat-card"><span>CUPS SERVED</span><strong>${cups}</strong><small>Goal: 50 today</small></div></div><div class="dashboard-grid"><div class="admin-card"><div class="admin-card-head"><h2>Live orders</h2><button data-admin-tab="orders">View all →</button></div><div style="overflow:auto">${ordersTable(state.orders.slice(0,5))}</div></div><div><div class="admin-card"><div class="admin-card-head"><h2>Popular today</h2></div><div class="popular-list">${menu.slice(0,4).map((p,i)=>`<div class="popular-row"><span style="--bg:${p.bg}">${p.emoji}</span><div><b>${p.name}</b><small>${[14,11,8,6][i]} sold</small></div><strong>${money(p.price)}</strong></div>`).join('')}</div></div><div class="delivery-box"><h3>Delivery promise</h3><p>Set the ETA customers see at checkout.</p><div>${[25,30,35,45].map(n=>`<button class="${n===35?'active':''}">${n} min</button>`).join('')}</div></div></div></div>`}
  else if(state.adminTab==='orders'){const filtered=state.orderFilter==='All'?state.orders:state.orders.filter(o=>o.status===state.orderFilter);$('#adminContent').innerHTML=`<div class="full-order-card"><div class="orders-head"><div><span class="kicker">Order management</span><h2>All orders</h2></div><div>${['All','New','Preparing','Ready','Out for delivery'].map(x=>`<button data-order-filter="${x}" class="${x===state.orderFilter?'active':''}">${x}</button>`).join('')}</div></div><div style="overflow:auto">${ordersTable(filtered)}</div></div>`}
  else if(state.adminTab==='menuadmin'){$('#adminContent').innerHTML=`<div class="full-order-card"><div class="orders-head"><div><span class="kicker">Catalogue</span><h2>Menu availability</h2></div><button class="active">+ Add item</button></div><div class="product-grid">${menu.map(p=>`<div class="popular-row" style="border:1px solid var(--line);padding:14px"><span style="--bg:${p.bg}">${p.emoji}</span><div><b>${p.name}</b><small>${money(p.price)} · In stock</small></div><button style="border:1px solid var(--line);background:white;padding:7px;font-size:8px">Edit</button></div>`).join('')}</div></div>`}
  else {$('#adminContent').innerHTML=`<div class="dashboard-grid"><div class="admin-card"><div class="admin-card-head"><h2>Active deliveries</h2><span class="kicker">${active.length} orders</span></div><div class="map-placeholder"><span class="map-pin store" style="left:44%;top:43%"><span>M</span></span>${active.slice(0,4).map((o,i)=>`<span class="map-pin" style="left:${[25,61,72,38][i]}%;top:${[30,25,62,70][i]}%"><span>${i+1}</span></span>`).join('')}</div></div><div class="admin-card"><div class="admin-card-head"><h2>Delivery queue</h2></div><div class="popular-list">${active.map(o=>`<div class="popular-row"><span style="--bg:#e8e3d8">🛵</span><div><b>${o.id} · ${o.name}</b><small>${o.address}<br>${o.status}</small></div><strong>${o.eta}m</strong></div>`).join('')}</div></div></div>`}
}
document.addEventListener('click',e=>{
  const goBtn=e.target.closest('[data-go]');if(goBtn){closeLayers();go(goBtn.dataset.go)}
  const add=e.target.closest('[data-add]');if(add){e.stopPropagation();openProduct(add.dataset.add)}
  const card=e.target.closest('[data-product]');if(card&&!e.target.closest('.heart'))openProduct(card.dataset.product);
  const cat=e.target.closest('[data-category]');if(cat){state.category=cat.dataset.category;renderProducts()}
  if(e.target.closest('#dietaryFilter')){state.plantOnly=!state.plantOnly;$('#dietaryFilter').classList.toggle('active',state.plantOnly);renderProducts()}
  if(e.target.closest('.heart')){e.stopPropagation();const b=e.target.closest('.heart');b.classList.toggle('active');b.textContent=b.classList.contains('active')?'♥':'♡';toast(b.classList.contains('active')?'Saved to favourites':'Removed from favourites')}
  const quick=e.target.closest('[data-quick-add]');if(quick)openProduct(quick.dataset.quickAdd);
  if(e.target.closest('#cartButton')||e.target.closest('#mobileCart')){renderCart();openLayer($('#cartDrawer'))}
  if(e.target.matches('[data-close]')||e.target.closest('[data-close]')||e.target.id==='overlay')closeLayers();
  const opt=e.target.closest('[data-option]');if(opt){opt.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));opt.classList.add('active');state.options[opt.dataset.option]=opt.dataset.value;updateModalPrice()}
  const mq=e.target.closest('[data-modal-qty]');if(mq){state.qty=Math.max(1,state.qty+Number(mq.dataset.modalQty));updateModalPrice()}
  if(e.target.closest('#confirmAdd'))addSelected();
  const cq=e.target.closest('[data-cart-qty]');if(cq){const i=Number(cq.dataset.cartQty),d=Number(cq.dataset.delta);state.cart[i].qty+=d;if(state.cart[i].qty<=0)state.cart.splice(i,1);save();renderCart()}
  const rem=e.target.closest('[data-remove]');if(rem){state.cart.splice(Number(rem.dataset.remove),1);save();renderCart()}
  if(e.target.closest('#checkoutButton'))openCheckout();
  const pay=e.target.closest('[data-payment]');if(pay){$$('[data-payment]').forEach(x=>x.classList.remove('active'));pay.classList.add('active');state.payment=pay.dataset.payment;$('#cardFields').style.display=state.payment==='Card'?'grid':'none'}
  if(e.target.closest('#trackButton')){const id=$('#trackInput').value.trim().toUpperCase();renderTracking(state.orders.find(o=>o.id===id))}
  const at=e.target.closest('[data-admin-tab]');if(at){state.adminTab=at.dataset.adminTab;$$('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x.dataset.adminTab===state.adminTab));renderAdmin()}
  const of=e.target.closest('[data-order-filter]');if(of){state.orderFilter=of.dataset.orderFilter;renderAdmin()}
  if(e.target.closest('#storeToggle')){const b=$('#storeToggle');b.classList.toggle('closed');b.querySelector('b').textContent=b.classList.contains('closed')?'Closed for orders':'Open for orders';toast(b.querySelector('b').textContent)}
  if(e.target.closest('#locationButton')){const next=prompt('Enter your delivery neighbourhood or postal code:',$('#headerLocation').textContent);if(next){$('#headerLocation').textContent=next;toast(`Delivery location updated to ${next}`)}}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-status-order]')){const o=state.orders.find(x=>x.id===e.target.dataset.statusOrder);o.status=e.target.value;if(o.status==='Delivered')o.eta=0;save();renderAdmin();toast(`${o.id} updated to ${o.status}`)}if(e.target.matches('[data-eta-order]')){const o=state.orders.find(x=>x.id===e.target.dataset.etaOrder);o.eta=Number(e.target.value);save();toast(`${o.id} ETA updated to ${o.eta} minutes`)}});
document.addEventListener('submit',e=>{if(e.target.id==='checkoutForm'){e.preventDefault();placeOrder(e.target)}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLayers();if(e.key==='Enter'&&e.target.id==='trackInput')renderTracking(state.orders.find(o=>o.id===e.target.value.trim().toUpperCase()))});
renderProducts();renderCart();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
